-- MySQL Script generated by MySQL Workbench
-- Fri Jan 19 22:27:56 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema rlanches
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rlanches` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `rlanches` ;

-- -----------------------------------------------------
-- Table `tb_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_users` ;

CREATE TABLE IF NOT EXISTS `tb_users` (
  `iduser` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `login` VARCHAR(64) NOT NULL,
  `pass` VARCHAR(256) NOT NULL,
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB;

INSERT INTO `tb_users` (`name`, `login`, `pass`, `active`) VALUES
('Mateus Lopes', 'Mateus', '$2y$10$ovc0sxTsr52icxqOxxmlj.DOb9F.aLuGTKTUL7P6sW8UdrSRMEb2q', 1),
('Jaime Nobrega', 'Jaime', '$2y$10$oUMD7CsMSUXqqHniyl93Q.bVSW3f.fHvJtGdqR8uYIneHQ1YWxMXy', 1),
('Filipe Lucas', 'Filipe', '$2y$10$kyTt1n7FSC0pG71CtakL8u1BjrAMiXR/StMnVhOrTCBajeNj.ZvoC', 1);

-- -----------------------------------------------------
-- Table `tb_promotions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_promotions` ;

CREATE TABLE IF NOT EXISTS `tb_promotions` (
  `idpromotions` INT(11) NOT NULL AUTO_INCREMENT,
  `iduser` INT(11) NOT NULL,
  `name` VARCHAR(128) NOT NULL,
  `description` LONGTEXT NOT NULL,
  `price` VARCHAR(32) NOT NULL,
  `image` VARCHAR(64) NOT NULL,
  `active` TINYINT(1) NOT NULL,
  `dtregister` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idpromotions`),
  CONSTRAINT `fk_tb_promotions_tb_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `tb_users` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_tb_promotions_tb_user1_idx` ON `tb_promotions` (`iduser` ASC);

INSERT INTO `tb_promotions` (`iduser`, `name`, `description`, `price`, `image`, `active`, `dtregister`) VALUES
(1, 'Dica de Refeição!', 'Coxa e Sobrecoxa Assada e Desossada com <br>Arroz, Feijão e Batata Assada', 'R$ 12,00', 'DSCN1499.jpg', 1, '2017-09-28 04:53:32'),
(1, 'HotDog Dogao', 'Descrição 1 + vantagens 1 + valores', '0', '', 0, '2017-09-29 21:47:33'),
(1, 'Comercial Bife + Suco', 'Descrição 2 + vantagens 2 + valores', 'R$ 10,00', 'comercial1.1.jpg', 0, '2017-09-30 12:57:01');

-- -----------------------------------------------------
-- Table `tb_userslogs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_userslogs` ;

CREATE TABLE IF NOT EXISTS `tb_userslogs` (
  `idpromotions` INT(11) NOT NULL AUTO_INCREMENT,
  `iduser` INT(11) NOT NULL,
  `deslog` VARCHAR(128) NOT NULL,
  `desip` VARCHAR(45) NOT NULL,
  `desuseragent` VARCHAR(128) NOT NULL,
  `dessessionid` VARCHAR(64) NOT NULL,
  `desurl` VARCHAR(128) NOT NULL,
  `dtregister` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idpromotions`),
  CONSTRAINT `fk_tb_userlogs_tb_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `tb_users` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_tb_userlogs_tb_user1_idx` ON `tb_userslogs` (`iduser` ASC);


-- -----------------------------------------------------
-- Table `tb_highlights`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_highlights` ;

CREATE TABLE IF NOT EXISTS `tb_highlights` (
  `idpromotions` INT(11) NOT NULL AUTO_INCREMENT,
  `iduser` INT(11) NOT NULL,
  `name` VARCHAR(128) NOT NULL,
  `description` LONGTEXT NOT NULL,
  `image` VARCHAR(64) NOT NULL,
  `active` TINYINT(1) NOT NULL,
  `dtregister` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idpromotions`),
  CONSTRAINT `fk_tb_highlights_tb_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `tb_users` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_tb_highlights_tb_user1_idx` ON `tb_highlights` (`iduser` ASC);

INSERT INTO `tb_highlights` (`iduser`, `name`, `description`, `image`, `active`, `dtregister`) VALUES
(1, 'Parmegianas', 'Opções:<br>- Filé de frango<br>- Contrafilé<br>- Filé mignon', 'LANCHES350.jpg', 1, '2017-09-28 04:53:32'),
(1, 'Lanches Crocantes', 'Opções:<br>- Filé de Frango Crocante<br>- Hambúguer Crocante', 'LANCHES108.jpg', 1, '2017-09-29 21:47:33'),
(1, 'Hambúrguer Artesanal', 'Deliciosos combos, lanches big (com 2 hambúrgues)', 'Imagem_141.jpg', 1, '2017-10-02 12:57:01'),
(1, 'Salgados Artesanais', 'Esfiha de frango, trouxinha de calabresa, peito de peru c/ queijo branco <br>e muito mais...', 'DSCN2085.jpg', 1, '2017-10-03 14:23:20');

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
